name = "line-recorder-bot-v2"
main = "src/index.tsx"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "line-recorder-bot-v2-db"
database_id = "36969a67-9a06-4cc4-972f-f528b1b17139" # Add your database id here

[vars]
LINE_CHANNEL_ACCESS_TOKEN = ""
LINE_CHANNEL_SECRET = ""
GEMINI_API_KEY = ""
BYPASS_LINE_VALIDATION = ""
