name = "line-recorder-bot-v2"
main = "src/index.tsx"
compatibility_date = "2026-02-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "line-recorder-bot-v2-db"
database_id = "36969a67-9a06-4cc4-972f-f528b1b17139" # Add your database id here
migrations_dir = "./migrations"

[[queues.producers]]
 queue = "line-bot-queue"
 binding = "LINE_BOT_QUEUE"

[[queues.consumers]]
 queue = "line-bot-queue"
 max_batch_size = 10
 max_batch_timeout = 5
